"""Deterministic media fixtures, generated by ffmpeg at test time.

Nothing here is committed. Every generator produces a file whose defining
property is asserted in tests/test_fixtures.py before any other test relies on
it — a fixture that cannot exhibit its defect makes downstream tests vacuous.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

W, H, FPS, DUR = 1920, 1080, 30, 12
TONE = f"sine=frequency=220:duration={DUR}"


def _ff(args: list[str]) -> None:
    subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", *args],
        check=True, capture_output=True, text=True,
    )


def _build(out: Path, volume_filter: str | None = None, itsoffset: float | None = None) -> Path:
    # CACHED ON DISK, ACROSS RUNS: every fixture generator in this file (this
    # one and the three below with their own inline `if out.exists()`) writes
    # once to tests/_fixtures/ and every later call — including in a LATER
    # pytest invocation, not just this session — returns the pre-existing file
    # without regenerating it. Editing this function's ffmpeg args, or a
    # fixture's own generation logic below, has NO EFFECT until the matching
    # file under tests/_fixtures/ is deleted.
    #
    # This is exactly the "test that stays green while asserting nothing"
    # failure this project exists to catch, one level up: mutating a fixture
    # generator to prove a positive-control test is load-bearing (Task 9 Step
    # 5, mutation 4) is INVALID unless you delete the cached output first —
    # measured live: mutating `rotated` without deleting
    # tests/_fixtures/rotated.mp4 left test_rotated_actually_carries_rotation
    # PASSING against the untouched old file. Deleting the cache first made it
    # correctly go RED. Always `rm` the relevant file(s) under
    # tests/_fixtures/ before running a mutation check against a fixture, and
    # restore them (or let them regenerate) before committing.
    if out.exists():
        return out
    args: list[str] = []
    args += ["-f", "lavfi", "-i", f"color=c=navy:s={W}x{H}:d={DUR}:r={FPS}"]
    if itsoffset is not None:
        args += ["-itsoffset", str(itsoffset)]
    args += ["-f", "lavfi", "-i", TONE]
    # An asymmetric mark so orientation is detectable: red box top-left,
    # green bar along the bottom. A flat colour field cannot reveal rotation.
    vf = (
        "drawbox=x=60:y=60:w=400:h=300:color=red@1:t=fill,"
        f"drawbox=x=0:y={H - 80}:w={W}:h=80:color=green@1:t=fill"
    )
    args += ["-vf", vf]
    if volume_filter:
        args += ["-af", volume_filter]
    args += ["-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest", str(out)]
    _ff(args)
    return out


@pytest.fixture(scope="session")
def fixture_dir() -> Path:
    d = Path(__file__).parent / "_fixtures"
    d.mkdir(exist_ok=True)
    return d


@pytest.fixture(scope="session")
def plain_av(fixture_dir: Path) -> Path:
    return _build(fixture_dir / "plain.mp4")


@pytest.fixture(scope="session")
def no_silence(fixture_dir: Path) -> Path:
    """Negative control: continuous tone, no silence anywhere."""
    return _build(fixture_dir / "no_silence.mp4")


@pytest.fixture(scope="session")
def silence_mid(fixture_dir: Path) -> Path:
    """Silence at 3.0-5.0s and 8.0-9.5s. The happy path."""
    return _build(
        fixture_dir / "silence_mid.mp4",
        volume_filter="volume=enable='between(t,3,5)+between(t,8,9.5)':volume=0",
    )


@pytest.fixture(scope="session")
def silence_at_zero(fixture_dir: Path) -> Path:
    """Silence from t=0. ffmpeg emits `silence_start: 0` — a BARE INTEGER, which
    a naive r'\\d+\\.\\d+' parser silently misses."""
    return _build(
        fixture_dir / "silence_at_zero.mp4",
        volume_filter="volume=enable='between(t,0,2)':volume=0",
    )


@pytest.fixture(scope="session")
def silence_to_eof(fixture_dir: Path) -> Path:
    """Silence running to the end. Measured: silence_end lands PAST the reported
    duration (e.g. 10.0078 against 10.000000), which inverts to a segment with
    start > end unless clamped."""
    return _build(
        fixture_dir / "silence_to_eof.mp4",
        volume_filter=f"volume=enable='between(t,9,{DUR})':volume=0",
    )


@pytest.fixture(scope="session")
def offset_streams(fixture_dir: Path) -> Path:
    """Audio starts 0.476009s after video; video starts at 0.000000. silencedetect
    reports the AUDIO timeline; cuts are applied to the VIDEO timeline, so the two
    diverge by that offset.

    Built with ffmpeg `-itsoffset 0.5`; the request lands at 0.476009 after
    container timescale rounding. It is SYNTHETIC and is not evidence about real
    capture hardware — earlier text here and in spec §4.1 read "as a real
    recorder produces", which attributed this file's own number to a recording
    nobody measured."""
    return _build(fixture_dir / "offset_streams.mp4", itsoffset=0.5)


@pytest.fixture(scope="session")
def rotated(fixture_dir: Path) -> Path:
    """1920x1080 carrying rotation=90, so it DISPLAYS as 1080x1920 portrait.

    Built in two passes: `-display_rotation` is an INPUT option, and the
    deprecated `-metadata:s:v rotate=` silently produces no side data at all.
    """
    out = fixture_dir / "rotated.mp4"
    # Same disk-cache hazard as `_build` above: mutating the two lines below
    # this check has no effect until tests/_fixtures/rotated.mp4 is deleted.
    if out.exists():
        return out
    flat = _build(fixture_dir / "_rot_flat.mp4")
    _ff(["-display_rotation", "90", "-i", str(flat), "-c", "copy", str(out)])
    return out


@pytest.fixture(scope="session")
def rotated_with_silence(fixture_dir: Path) -> Path:
    """Rotated (rotation=90 side data) AND containing silence gaps.

    `rotated` is a continuous tone with nothing to cut, so a cut through it
    short-circuits as a no-op copy and never exercises auto-editor's actual
    render path. This fixture carries the same silence pattern as
    `silence_mid` so a cut through it renders for real, while still being
    built the same two-pass way as `rotated`: `-display_rotation` is an INPUT
    option, and the deprecated `-metadata:s:v rotate=` produces no side data
    at all.
    """
    out = fixture_dir / "rotated_with_silence.mp4"
    # Same disk-cache hazard as `_build` above: mutating the logic below this
    # check has no effect until tests/_fixtures/rotated_with_silence.mp4 is
    # deleted.
    if out.exists():
        return out
    flat = _build(
        fixture_dir / "_rot_flat_silence.mp4",
        volume_filter="volume=enable='between(t,3,5)+between(t,8,9.5)':volume=0",
    )
    _ff(["-display_rotation", "90", "-i", str(flat), "-c", "copy", str(out)])
    return out


@pytest.fixture(scope="session")
def hf_project(fixture_dir: Path) -> Path:
    """A minimal HyperFrames project whose composition plays `assets/input.mp4`.

    Scaffolded once per session; the flow copies each stage's input over
    assets/input.mp4 before rendering.

    `data-no-timeline` on the root div: this composition is a static overlay
    with no GSAP-driven animation, so there is no `window.__timelines.main`
    for HyperFrames to ever register. Without this attribute, every render
    burns the full sub-composition-readiness timeout (measured: ~45s) waiting
    on a registration that was never coming, before doing any real work.
    Traced in the installed hyperframes CLI (`pollSubCompositionTimelines` in
    dist/cli.js): it polls every host carrying `data-composition-id` for that
    registration and only proceeds anyway, best-effort, once the timeout
    lapses. `data-no-timeline` is its own documented escape hatch for exactly
    this case. Measured effect: ~94s per render dropped to ~4s.
    """
    proj = fixture_dir / "hfproj"
    # Same disk-cache hazard as `_build` above (different check, same trap):
    # mutating the scaffold below has no effect until tests/_fixtures/hfproj/
    # is deleted.
    if (proj / "index.html").exists():
        return proj
    proj.mkdir(parents=True, exist_ok=True)
    (proj / "assets").mkdir(exist_ok=True)
    (proj / "hyperframes.json").write_text(
        '{"paths": {"blocks": "compositions", "assets": "assets"}}\n'
    )
    (proj / "index.html").write_text("""<!doctype html>
<html lang="en"><head><meta charset="UTF-8" />
<meta name="viewport" content="width=1920, height=1080" />
<style>*{margin:0;padding:0;box-sizing:border-box}
html,body{width:1920px;height:1080px;overflow:hidden;background:#000}
#footage{position:absolute;inset:0}#footage video{width:100%;height:100%;object-fit:contain}
#cap{position:absolute;bottom:120px;left:0;right:0;text-align:center;
font-size:64px;font-weight:700;color:#fff}</style></head>
<body><div id="root" data-composition-id="main" data-no-timeline data-start="0"
data-duration="6" data-width="1920" data-height="1080">
<div id="footage" class="clip" data-start="0" data-duration="6" data-track-index="0">
<video src="assets/input.mp4" data-media data-start="0" data-duration="6"></video></div>
<div id="cap" class="clip" data-start="0" data-duration="6" data-track-index="1">caption</div>
</div></body></html>
""")
    return proj


@pytest.fixture(scope="session")
def black_frame(fixture_dir: Path) -> Path:
    """A solid black clip, correctly sized and encoded so it is a plausible
    render output rather than a degenerate file -- the positive control for
    the caption stage's mean_luma black-frame guard.

    Deliberately built WITHOUT the red/green orientation marks _build() draws
    on every other fixture: those marks would lift the average luma well
    above the limited-range black floor and defeat the point of this fixture.
    """
    out = fixture_dir / "black_frame.mp4"
    # Same disk-cache hazard as `_build` above: mutating the args below this
    # check has no effect until tests/_fixtures/black_frame.mp4 is deleted.
    if out.exists():
        return out
    _ff(
        [
            "-f", "lavfi", "-i", f"color=c=black:s={W}x{H}:d={DUR}:r={FPS}",
            "-f", "lavfi", "-i", TONE,
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac",
            "-shortest", str(out),
        ]
    )
    return out


@pytest.fixture(scope="session")
def black_after_head(fixture_dir: Path) -> Path:
    """Bright for the first second, black for the eleven after it.

    The positive control for WHERE the luma guard samples, which the
    uniformly-black `black_frame` fixture structurally cannot be: a probe that
    reads only the head of the file measures this clip at YAVG 235 and finds no
    black pixels at all, while the same clip sampled across its whole timeline
    measures YAVG 34.25 and 91.67% black pixels. `black_frame` agrees with both
    samplings, so it cannot tell "checks the video" from "checks the first 0.67
    seconds" -- measured, that is exactly the hole a 20-frame probe sat in.

    Video only: this fixture exists for the luma probe, and an audio track
    would add nothing it measures.
    """
    out = fixture_dir / "black_after_head.mp4"
    # Same disk-cache hazard as `_build` above: mutating the args below this
    # check has no effect until tests/_fixtures/black_after_head.mp4 is deleted.
    if out.exists():
        return out
    _ff(
        [
            "-f", "lavfi", "-i", f"color=c=white:s={W}x{H}:d=1:r={FPS}",
            "-f", "lavfi", "-i", f"color=c=black:s={W}x{H}:d={DUR - 1}:r={FPS}",
            "-filter_complex", "[0:v][1:v]concat=n=2:v=1:a=0[v]",
            "-map", "[v]", "-c:v", "libx264", "-pix_fmt", "yuv420p", str(out),
        ]
    )
    return out
