"""Deterministic media fixtures, generated by ffmpeg at test time.

Nothing here is committed. Every generator produces a file whose defining
property is asserted in tests/test_fixtures.py before any other test relies on
it — a fixture that cannot exhibit its defect makes downstream tests vacuous.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

W, H, FPS, DUR = 1920, 1080, 30, 12
TONE = f"sine=frequency=220:duration={DUR}"


def _ff(args: list[str]) -> None:
    subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", *args],
        check=True, capture_output=True, text=True,
    )


def _build(out: Path, volume_filter: str | None = None, itsoffset: float | None = None) -> Path:
    if out.exists():
        return out
    args: list[str] = []
    args += ["-f", "lavfi", "-i", f"color=c=navy:s={W}x{H}:d={DUR}:r={FPS}"]
    if itsoffset is not None:
        args += ["-itsoffset", str(itsoffset)]
    args += ["-f", "lavfi", "-i", TONE]
    # An asymmetric mark so orientation is detectable: red box top-left,
    # green bar along the bottom. A flat colour field cannot reveal rotation.
    vf = (
        "drawbox=x=60:y=60:w=400:h=300:color=red@1:t=fill,"
        f"drawbox=x=0:y={H - 80}:w={W}:h=80:color=green@1:t=fill"
    )
    args += ["-vf", vf]
    if volume_filter:
        args += ["-af", volume_filter]
    args += ["-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest", str(out)]
    _ff(args)
    return out


@pytest.fixture(scope="session")
def fixture_dir() -> Path:
    d = Path(__file__).parent / "_fixtures"
    d.mkdir(exist_ok=True)
    return d


@pytest.fixture(scope="session")
def plain_av(fixture_dir: Path) -> Path:
    return _build(fixture_dir / "plain.mp4")


@pytest.fixture(scope="session")
def no_silence(fixture_dir: Path) -> Path:
    """Negative control: continuous tone, no silence anywhere."""
    return _build(fixture_dir / "no_silence.mp4")


@pytest.fixture(scope="session")
def silence_mid(fixture_dir: Path) -> Path:
    """Silence at 3.0-5.0s and 8.0-9.5s. The happy path."""
    return _build(
        fixture_dir / "silence_mid.mp4",
        volume_filter="volume=enable='between(t,3,5)+between(t,8,9.5)':volume=0",
    )


@pytest.fixture(scope="session")
def silence_at_zero(fixture_dir: Path) -> Path:
    """Silence from t=0. ffmpeg emits `silence_start: 0` — a BARE INTEGER, which
    a naive r'\\d+\\.\\d+' parser silently misses."""
    return _build(
        fixture_dir / "silence_at_zero.mp4",
        volume_filter="volume=enable='between(t,0,2)':volume=0",
    )


@pytest.fixture(scope="session")
def silence_to_eof(fixture_dir: Path) -> Path:
    """Silence running to the end. Measured: silence_end lands PAST the reported
    duration (e.g. 10.0078 against 10.000000), which inverts to a segment with
    start > end unless clamped."""
    return _build(
        fixture_dir / "silence_to_eof.mp4",
        volume_filter=f"volume=enable='between(t,9,{DUR})':volume=0",
    )


@pytest.fixture(scope="session")
def offset_streams(fixture_dir: Path) -> Path:
    """Audio starts ~0.48s after video, as a real recorder produces. silencedetect
    reports the AUDIO timeline; cuts are applied to the VIDEO timeline."""
    return _build(fixture_dir / "offset_streams.mp4", itsoffset=0.5)


@pytest.fixture(scope="session")
def rotated(fixture_dir: Path) -> Path:
    """1920x1080 carrying rotation=90, so it DISPLAYS as 1080x1920 portrait.

    Built in two passes: `-display_rotation` is an INPUT option, and the
    deprecated `-metadata:s:v rotate=` silently produces no side data at all.
    """
    out = fixture_dir / "rotated.mp4"
    if out.exists():
        return out
    flat = _build(fixture_dir / "_rot_flat.mp4")
    _ff(["-display_rotation", "90", "-i", str(flat), "-c", "copy", str(out)])
    return out


@pytest.fixture(scope="session")
def rotated_with_silence(fixture_dir: Path) -> Path:
    """Rotated (rotation=90 side data) AND containing silence gaps.

    `rotated` is a continuous tone with nothing to cut, so a cut through it
    short-circuits as a no-op copy and never exercises auto-editor's actual
    render path. This fixture carries the same silence pattern as
    `silence_mid` so a cut through it renders for real, while still being
    built the same two-pass way as `rotated`: `-display_rotation` is an INPUT
    option, and the deprecated `-metadata:s:v rotate=` produces no side data
    at all.
    """
    out = fixture_dir / "rotated_with_silence.mp4"
    if out.exists():
        return out
    flat = _build(
        fixture_dir / "_rot_flat_silence.mp4",
        volume_filter="volume=enable='between(t,3,5)+between(t,8,9.5)':volume=0",
    )
    _ff(["-display_rotation", "90", "-i", str(flat), "-c", "copy", str(out)])
    return out
